### ISSUE TITLE
NumberFormatException while running startup.sh

### ISSUE THREAD

**Issue by susenj** [CiscoIOx/modbus_simulator#1]
Running startup.sh file on Windows machine leaves the _NumberFormatException_ .
Though it also says _Modbus simulator started_. 

Looking at the source files, I couldn't reckon if these are harmless.

>  true: false: false: 5: 2: 4: 2: 5: 5: 4: false: true:host - 0.0.0.0
> port - 502
> Jun 28, 2016 8:25:33 PM com.cisco.iox.simulators.modbus.SimulatorDriver setup
> SEVERE: Error -
> java.lang.NumberFormatException: For input string: "true"
>         at java.lang.NumberFormatException.forInputString(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveHandler.getRegisterStartAndCount(ModbusSlaveHandler.java:51)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveHandler.loadRegisters(ModbusSlaveHandler.java:86)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveHandler.<init>(ModbusSlaveHandler.java:46)
>         at com.cisco.iox.simulators.modbus.ModbusSlave.<init>(ModbusSlave.java:19)
>         at com.cisco.iox.simulators.modbus.SimulatorDriver.setup(SimulatorDriver.java:101)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveSimulator.main(ModbusSlaveSimulator.java:15)
> 
> java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "true"
>         at com.cisco.iox.simulators.modbus.SimulatorDriver.setup(SimulatorDriver.java:104)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveSimulator.main(ModbusSlaveSimulator.java:15)
> Caused by: java.lang.NumberFormatException: For input string: "true"
>         at java.lang.NumberFormatException.forInputString(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveHandler.getRegisterStartAndCount(ModbusSlaveHandler.java:51)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveHandler.loadRegisters(ModbusSlaveHandler.java:86)
>         at com.cisco.iox.simulators.modbus.ModbusSlaveHandler.<init>(ModbusSlaveHandler.java:46)
>         at com.cisco.iox.simulators.modbus.ModbusSlave.<init>(ModbusSlave.java:19)
>         at com.cisco.iox.simulators.modbus.SimulatorDriver.setup(SimulatorDriver.java:101)
>         ... 1 more
> Modbus simulator started

**Comment by savinirsch** [comment]
You need to have the dataset, exactly in this order
address ranges followed by types followed by table of values.
The column numbers should exactly match.

40001-1,40002-1,40003-2,40005-2
short,short,float,float
40,20,9.99,30.11

I can see some "true" in the address range column read by the simulator.

java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "true"
at com.cisco.iox.simulators.modbus.SimulatorDriver.setup(SimulatorDriver.java:104)
at com.cisco.iox.simulators.modbus.ModbusSlaveSimulator.main(ModbusSlaveSimulator.java:15)
Caused by: java.lang.NumberFormatException: For input string: "true"

Please check the dataset.
